[tool.cibuildwheel]
#before-all-linux = "./ci/install_go.sh"
#before-all-windows = "./ci/install_go.sh"
#environment = "PATH=$PATH:/usr/local/go/bin"
#before-build = "go version"
#build = "*cp36-manylinux_i686*"
