name: Build and Publish

on:
  push:
    branches: [ capi ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest] #,macOS-latest,ubuntu-latest,windows-latest]
    runs-on: ${{ matrix.os }}       
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'
    - name: check go installation
      run: |
        which go
        go version
    - name: Install MinGW (Windows only)
      if: matrix.os == 'windows-latest'
      run: choco install mingw --version 13.2.0 --x86 --force
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.5'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cibuildwheel
    - name: Install package
      run: |
        python -m pip install .
        pip install pytest
    - name: Run tests
      run: |
        pytest -s -v
    - name: Build wheels
      run: |
        python -m cibuildwheel --output-dir wheelhouse
