name: Build and Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          #- goos: windows
          #  goarch: amd64
          #  ext: dll
          #  runner: windows-latest
          - goos: linux
            goarch: amd64
            ext: so
            runner: ubuntu-latest
          #- goos: darwin
          #  goarch: amd64
          #  ext: dylib
          #  runner: macos-latest
    runs-on: ${{ matrix.runner }}       
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'
    - name: Install MinGW (Windows only)
      if: matrix.goos == 'windows'
      run: choco install mingw --version 13.2.0 --force
    - name: Cross-Compile Go Library
      working-directory: jsonatago/golang
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        go build -o ../../dist/jsonatago-${{ matrix.goos }}-${{ matrix.goarch }}.so -buildmode=c-shared main.go
    - name: Upload .so files
      uses: actions/upload-artifact@v2
      with:
        name: shared-libs
        path: dist/*
  build_wheels:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest] #], windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Download shared-libs
        uses: actions/download-artifact@v2
        with:
          name: shared-libs
          path: ./dist

      - name: List package contents
        run: find . -type f

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
