name: Build and Publish

on:
  push:
    branches: [ capi ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}       
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'
    - name: Install MinGW (Windows only)
      if: matrix.os == 'windows-latest'
      run: choco install mingw --version 13.2.0 --force
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cibuildwheel
    - name: Build wheels
      run: |
        python -m cibuildwheel --output-dir wheelhouse
    - name: List package contents
      run: find . -type f